# escape=`
FROM plugins/base:windows-1903-amd64@sha256:0281767a55c9425635d2351e297c8b78d664a7f46a27841473079cae81fc9f69

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone GitHub Release Download" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

ADD release/windows/amd64/drone-github-release-download.exe C:/bin/drone-github-release-download.exe
ENTRYPOINT [ "C:\\bin\\drone-github-release-download.exe" ]
