FROM plugins/base:multiarch@sha256:38ceaebc2834efcdb94fce3aa9db13d0d314ad67aa7bf144178b90b6c7ea39a7

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" \
  org.label-schema.name="Drone GitHub Release Download" \
  org.label-schema.vendor="Drone.IO Community" \
  org.label-schema.schema-version="1.0"

ADD release/linux/amd64/drone-github-release-download /bin/
ENTRYPOINT [ "/bin/drone-github-release-download" ]
