FROM plugins/base:multiarch@sha256:354afa05bf94cfe6810b3fa0f603a51641aa310e18d9cc7bd0de9f8e5b5e1980

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" \
  org.label-schema.name="Drone GitHub Release Download" \
  org.label-schema.vendor="Drone.IO Community" \
  org.label-schema.schema-version="1.0"

ADD release/linux/arm/drone-github-release-download /bin/
ENTRYPOINT [ "/bin/drone-github-release-download" ]
