FROM plugins/base:multiarch@sha256:90c1beae63a836eff6c055ccfd95d17843eddc94c84c518c0275636874af88a4

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" \
  org.label-schema.name="Drone GitHub Release Download" \
  org.label-schema.vendor="Drone.IO Community" \
  org.label-schema.schema-version="1.0"

ADD release/linux/arm64/drone-github-release-download /bin/
ENTRYPOINT [ "/bin/drone-github-release-download" ]
