FROM plugins/base:multiarch@sha256:ce008a16b4be4b65065f3df08041de267c09fa2f6a1a51a825d8a20f66360f75

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" \
  org.label-schema.name="Drone GitHub Release Download" \
  org.label-schema.vendor="Drone.IO Community" \
  org.label-schema.schema-version="1.0"

ADD release/linux/arm/drone-github-release-download /bin/
ENTRYPOINT [ "/bin/drone-github-release-download" ]
