FROM plugins/base:multiarch@sha256:9ad48ce093ab51f5bbf409b4e4d1f09093f406621d0e969c8f99e576fb4c535e

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" \
  org.label-schema.name="Drone GitHub Release Download" \
  org.label-schema.vendor="Drone.IO Community" \
  org.label-schema.schema-version="1.0"

ADD release/linux/arm64/drone-github-release-download /bin/
ENTRYPOINT [ "/bin/drone-github-release-download" ]
