# escape=`
FROM plugins/base:windows-1909-amd64@sha256:55435a3a3fb533ca2e842fc4dfd6c5087a6f5ab1885e9f7949129fd6ae0601d5

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone GitHub Release Download" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

ADD release/windows/amd64/drone-github-release-download.exe C:/bin/drone-github-release-download.exe
ENTRYPOINT [ "C:\\bin\\drone-github-release-download.exe" ]
