FROM plugins/base:multiarch@sha256:69ac4013f0eed21e7e06541c6099cedbcd85ad5b771fe102ab8381ba16badb77

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" \
  org.label-schema.name="Drone GitHub Release Download" \
  org.label-schema.vendor="Drone.IO Community" \
  org.label-schema.schema-version="1.0"

ADD release/linux/amd64/drone-github-release-download /bin/
ENTRYPOINT [ "/bin/drone-github-release-download" ]
