FROM plugins/base:multiarch@sha256:53584c7c5cae6ad20f43d346811a0bee55af073fc502243ae34b9876ad4cd8ac

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" \
  org.label-schema.name="Drone GitHub Release Download" \
  org.label-schema.vendor="Drone.IO Community" \
  org.label-schema.schema-version="1.0"

ADD release/linux/arm/drone-github-release-download /bin/
ENTRYPOINT [ "/bin/drone-github-release-download" ]
