# escape=`
FROM plugins/base:windows-ltsc2022-amd64@sha256:66cf479fa173245f61c60fae9b5e9783614e3493eb19add3f7122f8523ae3cae

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone GitHub Release" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

ADD release/windows/amd64/drone-github-release-download.exe C:/bin/drone-github-release-download.exe
ENTRYPOINT [ "C:\\bin\\drone-github-release-download.exe" ]
