FROM plugins/base:multiarch@sha256:8a1292e50d92978d6f3d59579e706e28855fd9ddd361ca029b176970624ce08e

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" \
  org.label-schema.name="Drone GitHub Release Download" \
  org.label-schema.vendor="Drone.IO Community" \
  org.label-schema.schema-version="1.0"

ADD release/linux/arm64/drone-github-release-download /bin/
ENTRYPOINT [ "/bin/drone-github-release-download" ]
