# escape=`
FROM plugins/base:windows-ltsc2022-amd64@sha256:dcdb6e7683d5d7cfc0a18644b908a9b9529d1c74ff3c61bcfce3a3e26c970e3e

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone GitHub Release" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

ADD release/windows/amd64/drone-github-release-download.exe C:/bin/drone-github-release-download.exe
ENTRYPOINT [ "C:\\bin\\drone-github-release-download.exe" ]
