FROM plugins/base:multiarch@sha256:f4da47b6fcdaa7a66853f4a6ee1dae7c00a734e40c0b901e0145d3c64588881d

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" \
  org.label-schema.name="Drone GitHub Release Download" \
  org.label-schema.vendor="Drone.IO Community" \
  org.label-schema.schema-version="1.0"

ADD release/linux/amd64/drone-github-release-download /bin/
ENTRYPOINT [ "/bin/drone-github-release-download" ]
