# escape=`
FROM plugins/base:windows-1903-amd64@sha256:076dca8f5d3ab0e3178deb3cea7764daabc8a3864f50fddc858d5de786b8474e

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone GitHub Release Download" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

ADD release/windows/amd64/drone-github-release-download.exe C:/bin/drone-github-release-download.exe
ENTRYPOINT [ "C:\\bin\\drone-github-release-download.exe" ]
