# escape=`
FROM plugins/base:windows-1903-amd64@sha256:2ec10e55c544789dd46f83b28b9120750953e1bf49c33301f9bb4cd159715859

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone GitHub Release Download" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

ADD release/windows/amd64/drone-github-release-download.exe C:/bin/drone-github-release-download.exe
ENTRYPOINT [ "C:\\bin\\drone-github-release-download.exe" ]
